kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: ${APPLICATION_NAME}
  iconClass: icon-python
objects:
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${APPLICATION_NAME}
      annotations:
        description: Defines how to build the application from a dockerfile
        template.alpha.openshift.io/wait-for-ready: "true"
      labels:
        template: ${APPLICATION_NAME}
    spec:
      source:
        git:
          uri: "${SOURCE_REPOSITORY_URL}"
          ref: "${BRANCH}"
        contextDir: "${CONTEXT_DIRECTORY}"
        dockerfile: Dockerfile
      output:
        to:
          kind: DockerImage
          name: ${APPLICATION_NAME}:latest
        pushSecret:
          name: dockerhub
parameters:
  - name: APPLICATION_NAME
    displayName: Application Name
    description: The name of the application - used for resource names and labels
    value: telemetry-receiver
    required: true
  - name: SOURCE_REPOSITORY_URL
    displayName: Source Repository URL
    description: The URL for the application git repository
    value: https://github.com/kringen/anomoly-detection
    required: true
  - name: CONTEXT_DIRECTORY
    displayName: Context Directory
    description: Directory containing application in source repository.
    value: /app/telemetry_receiver
    required: false
  - name: REPLICA_COUNT
    description: Number of replicas to run
    value: "1"
    required: true
  - name: PORT
    description: Port on which the application listens.
    value: "8080"
    required: false
  - name: SOURCE_IMAGE_NAME
    description: Name of the source/base image.
    value: nodejs:14-ubi7
    required: false
  - name: SOURCE_IMAGE_NAMESPACE
    description: "namespace where the source/base image resides."
    value: openshift
    required: false
  - name: RESOURCE_LIMIT_MEMORY
    description: "Limit the memory consumed by a pod before it is destroyed and re-created."
    value: 512Mi